[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_market = "BNt9yPhijSp8XemxX3zkyscXvoYoY5hWm3arqpu7VuX8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/star/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
